### ISSUE TITLE
Doesn't work  LOL

### ISSUE THREAD

**Issue by Hardwaregore** [TechDudie/TechEditOfficial#1]
@TechDudie 

It doesn't even work. LOL

Look at da video

https://user-images.githubusercontent.com/88296644/163869191-a50c50e1-6d77-4eb4-84cb-71c464f251d7.mp4

**Comment by TechDudie** [comment]
Doesn't work LOL

@Hardwaregore It doesn't even work. LOL

Look at da photo
![BF08582E-B44F-426D-93D7-0D0505778F74](https://user-images.githubusercontent.com/73961295/164252090-794beedf-a58e-48e8-97bb-0cd6feaefec2.png)
